pomodoro/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'pomodoro'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

tasks/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from tasks import views

urlpatterns = [
    path('', TemplateView.as_view(template_name = 'index.html'), name = 'index'),
    path('about', views.About.as_view(), name = 'about'),
    path('tasks/', include('tasksapp.urls')),
    path('pomodoro/', include('pomodoro.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('health-check/', include('health_check.urls')),
]

tasksapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from tasksapp.views import context, milestone, project, scope, status, sticky, task, usersettings,\
    goal

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name='tasks-index'),

    path('context/', context.ContextList.as_view(), name='context-list'),
    path('context/add/', context.ContextCreate.as_view(), name='context-add'),
    path('context/<int:pk>/', context.ContextUpdate.as_view(), name='context-edit'),
    path('context/<int:pk>/delete/', context.ContextDelete.as_view(), name='context-delete'),

    path('goal/', goal.ListView.as_view(), name='goal-list'),
    path('goal/add/', goal.CreateView.as_view(), name='goal-add'),
    path('goal/<int:pk>/', goal.UpdateView.as_view(), name='goal-edit'),
    path('goal/<int:pk>/delete/', goal.DeleteView.as_view(), name='goal-delete'),

    path('milestone/', milestone.MilestoneList.as_view(), name='milestone-list'),
    path('milestone/add/', milestone.MilestoneCreate.as_view(), name='milestone-add'),
    path('milestone/<int:pk>/', milestone.MilestoneUpdate.as_view(), name='milestone-edit'),
    path('milestone/<int:pk>/delete/', milestone.MilestoneDelete.as_view(), name='milestone-delete'),
    path('milestone/<int:pk>/finish/', milestone.MilestoneFinish.as_view(), name='milestone-finish'),
    path('milestone/<int:pk>/report/', milestone.Report.as_view(), name='milestone-report'),
    path('milestone/<slug:pk>/setup', milestone.Setup.as_view(), name='milestone-setup'),
    path('milestone/<int:milestone_pk>/add/task/<int:task_pk>', milestone.setup_add_task, name='milestone-add-task'),

    path('project/', project.ProjectList.as_view(), name='project-list'),
    path('project/add/', project.ProjectCreate.as_view(), name='project-add'),
    path('project/<int:pk>/', project.ProjectUpdate.as_view(), name='project-edit'),
    path('project/<int:pk>/delete/', project.ProjectDelete.as_view(), name='project-delete'),

    path('scope/', scope.ListView.as_view(), name='scope-list'),
    path('scope/add/', scope.CreateView.as_view(), name='scope-add'),
    path('scope/<int:pk>/', scope.UpdateView.as_view(), name='scope-edit'),
    path('scope/<int:pk>/delete/', scope.DeleteView.as_view(), name='scope-delete'),

    path('status/', status.StatusList.as_view(), name='status-list'),
    path('status/add/', status.StatusCreate.as_view(), name='status-add'),
    path('status/<int:pk>/', status.StatusUpdate.as_view(), name='status-edit'),
    path('status/<int:pk>/delete/', status.StatusDelete.as_view(), name='status-delete'),

    path('task/my/', task.MyTaskList.as_view(), name='my-task-list'),
    path('task/all/', task.AllTaskList.as_view(), name='all-task-list'),
    path('task/add/', task.TaskCreate.as_view(), name='task-add'),
    path('task/<int:pk>/', task.TaskUpdate.as_view(), name='task-edit'),
    path('task/<int:pk>/delete/', task.TaskDelete.as_view(), name='task-delete'),
    path('task/<int:task_pk>/select-new-dependency/', task.SelectNewDependency.as_view(), name='task-select-new-dependency'),
    path('task/<int:taskPk>/done', task.task_done, name='task-done'),
    path('task/<int:taskPk>/logWork', task.logWork, name='task-log-work'),

    path('usersettings/', usersettings.Update.as_view(), name = 'usersettings-edit'),

# special actions on tasks
    path('task/<int:task_pk>/split', task.TaskSplitView.as_view(), name = 'task-split'),
    path('task/<int:task_pk>/add-dependency/<int:dependency_pk>/', task.add_dependency, name = 'task-add-dependency'),
    path('task/<int:task_pk>/remove-dependency/<int:dependency_pk>/', task.remove_dependency, name = 'task-remove-dependency'),
    path('task/<int:task_pk>/prio-up', task.prio_up, name = 'task-prio-up'),

# handling stickiness
    path('sticky/project/<int:project_pk>/set', sticky.sticky_project_set, name = 'sticky-project-set'),
    path('sticky/project/all/unset', sticky.sticky_project_unset, name = 'sticky-project-unset-all'),
    path('sticky/scope/<int:scope_pk>/set', sticky.sticky_scope_set, name = 'sticky-scope-set'),
    path('sticky/scope/all/unset', sticky.sticky_scope_unset, name = 'sticky-scope-unset-all'),
]

tasksapp/models.py
from datetime import date

from django.contrib.auth.models import User

from django.db import models

from django.urls import reverse
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    def __str__(self):
        return self.name

class Context(models.Model):
    name = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('context-edit', kwargs={'pk': self.pk})

class Goal(models.Model):
    name = models.CharField(max_length = 20)
    simple = models.TextField()
    measurable = models.TextField()
    # TODO add metric links
    actionable = models.TextField()
    # TODO add links to tasks as 'actions'
    reasonable = models.TextField()
    timebound = models.DateField()

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('goal-edit', kwargs={'pk': self.pk})

class Scope(models.Model):
    name = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('scope-edit', kwargs={'pk': self.pk})

class UserSettings(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    pomodoro_duration = models.PositiveSmallIntegerField(default = 25)
    def __str__(self):
        return str(self.user)
    def get_absolute_url(self):
        return reverse('usersettings-edit')

class Project(models.Model):
    name = models.CharField(max_length=20)
    active = models.BooleanField(default=True)
    description = models.TextField(blank=True)
    scope = models.ForeignKey(Scope, blank = True, null = True, on_delete = models.PROTECT)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('project-edit', kwargs={'pk': self.pk})

class Milestone(models.Model):
    name = models.CharField(max_length=20)
    project = models.ForeignKey(Project, blank = True, null = True, on_delete = models.SET_NULL)
    datetime_to_pass = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    happened = models.BooleanField(default=False)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('milestone-edit', kwargs={'pk': self.pk})

class Status(models.Model):
    name = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    is_done = models.BooleanField(default = False)
    is_new = models.BooleanField(default = False)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('status-edit', kwargs={'pk': self.pk})

class TaskEnhancedManager(models.Manager):
    def create(self, *args, **kwargs):
        task = models.Manager.create(self, *args, **kwargs)
        task.full_clean()
        return task

class Task(models.Model):
    objects = TaskEnhancedManager()

    # basic information
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    dateCreated = models.DateField(default=date.today)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    shared = models.BooleanField(default=False)

    # categorisation
    categories = models.ManyToManyField(Category, blank=True)
    context = models.ForeignKey(Context, blank = True, null = True, on_delete = models.SET_NULL)
    goals = models.ManyToManyField(Goal, blank = True)
    project = models.ForeignKey(Project, blank = True, null = True, on_delete = models.CASCADE)
    scope = models.ForeignKey(Scope, blank = True, null = True, on_delete = models.PROTECT)

    # state
    status = models.ForeignKey(Status, on_delete=models.PROTECT)
    assignee = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='assigned_tasks')
    milestone = models.ForeignKey(
        Milestone,
        on_delete = models.PROTECT,
        null = True,
        blank = True)

    @property
    def blocked(self):
        blockers = self.get_all_transient_blockers()
        for blocker in blockers:
            if not blocker.status.is_done:
                return True
        return False

    # generators
    @staticmethod
    def get_initials(request):
        try:
            sticky_project_pk = request.session['sticky_project']
        except:
            sticky_project_pk = None

        try:
            sticky_scope_pk = request.session['sticky_scope']
        except:
            sticky_scope_pk = None

        return {
            'owner': request.user,
            'project': sticky_project_pk,
            'scope': sticky_scope_pk,
            'status': Status.objects.filter(is_new = True).first()
        }

    # priority
    due_date = models.DateField(null = True, blank = True)
    priorityPoints = models.PositiveSmallIntegerField(default=1)
    priority_sum = models.IntegerField(default = 1, editable = False)

    def calc_priority_sum(self):
        result = self.priorityPoints
        if self.id is not None:
            dependants = Task.objects.filter(dependencies = self)
            for dependant in dependants:
                result += dependant.priority_sum
        return result

    # dependency
    dependencies = models.ManyToManyField('Task', blank = True, related_name = 'blocker')

    def update_priority_sum(self):
        self.priority_sum = self.calc_priority_sum()
        self.save()

    def get_all_transient_blockers(self):
        # TODO rename to "dependencies"
        all_transient_blockers = set()
        self_dependants = self.dependencies.all()
        for self_dependant in self_dependants:
            if self_dependant not in all_transient_blockers:
                all_transient_blockers.add(self_dependant)
                all_transient_blockers.update(self_dependant.get_all_transient_blockers())
        return all_transient_blockers

    def get_all_transient_dependants(self):
        all_transient_dependants = set()
        self_blockers = Task.objects.filter(dependencies = self)
        for self_blocker in self_blockers:
            if self_blocker not in all_transient_dependants:
                all_transient_dependants.add(self_blocker)
                all_transient_dependants.update(self_blocker.get_all_transient_dependants())
        return all_transient_dependants

    # repeating
    is_repeating = models.BooleanField(default = False)

    # effort
    estimation = models.PositiveSmallIntegerField(default=1)
    logged = models.PositiveSmallIntegerField(default=0)

    def clean(self):
        models.Model.clean(self)
        self.update_priority_sum()

    def save(self, *args, **kwargs):
        super(Task, self).save(*args, **kwargs)
        for dependency in self.dependencies.all():
            dependency.full_clean()
            dependency.save()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('task-edit', kwargs={'pk': self.pk})

class Workflow(models.Model):
    pass

tasksapp/views/context.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from django.urls import reverse_lazy

from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView

from tasksapp.models import Context

class ContextCreate(LoginRequiredMixin, CreateView):
    model = Context
    fields = '__all__'
    
    def form_valid(self, form):
        # add success message
        messages.success(self.request, 'Context created successfully.')
        return super().form_valid(form)

class ContextUpdate(LoginRequiredMixin, UpdateView):
    model = Context
    fields = '__all__'
    
    def form_valid(self, form):
        # add success message
        messages.success(self.request, 'Context saved successfully.')
        return super().form_valid(form)

class ContextDelete(LoginRequiredMixin, DeleteView):
    model = Context
    success_url = reverse_lazy('context-list')

class ContextList(LoginRequiredMixin, ListView):
    model = Context

tasksapp/views/goal.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from django.urls import reverse_lazy

from django.views.generic.edit import CreateView, DeleteView, UpdateView

from tasksapp.models import Scope, Goal
from django.views.generic.list import ListView
from tasksapp.forms import GoalForm

class CreateView(LoginRequiredMixin, CreateView):
    model = Goal
    form_class = GoalForm
    
    def form_valid(self, form):
        # add success message
        messages.success(self.request, 'Goal created successfully.')
        return super().form_valid(form)

class UpdateView(LoginRequiredMixin, UpdateView):
    model = Goal
    form_class = GoalForm
    
    def form_valid(self, form):
        # add success message
        messages.success(self.request, 'Goal saved successfully.')
        return super().form_valid(form)

class DeleteView(LoginRequiredMixin, DeleteView):
    model = Goal
    success_url = reverse_lazy('goal-list')

class ListView(LoginRequiredMixin, ListView):
    model = Goal

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        if 'sticky_scope' in self.request.session:
            context['sticky_scope'] = Scope.objects.get(pk = self.request.session['sticky_scope'])
        return context

tasksapp/views/project.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from django.urls import reverse_lazy

from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView

from tasksapp.models import Project, Scope

class ProjectCreate(LoginRequiredMixin, CreateView):
    model = Project
    fields = '__all__'

    def get_initial(self):
        sticky_scope = None
        if 'sticky_scope' in self.request.session:
            sticky_scope = self.request.session['sticky_scope']

        return {
            'scope': sticky_scope
        }
    
    def form_valid(self, form):
        # add success message
        messages.success(self.request, 'Project created successfully.')
        return super().form_valid(form)

class ProjectUpdate(LoginRequiredMixin, UpdateView):
    model = Project
    fields = '__all__'
    
    def form_valid(self, form):
        # add success message
        messages.success(self.request, 'Project saved successfully.')
        return super().form_valid(form)

class ProjectDelete(LoginRequiredMixin, DeleteView):
    model = Project
    success_url = reverse_lazy('project-list')


class ProjectList(LoginRequiredMixin, ListView):
    model = Project

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProjectList, self).get_context_data(**kwargs)
        context['project_list'] = context['project_list'].filter(active=True)
        if 'sticky_project' in self.request.session:
            context['sticky_project'] = Project.objects.get(pk = self.request.session['sticky_project'])
        if 'sticky_scope' in self.request.session:
            context['sticky_scope'] = Scope.objects.get(pk = self.request.session['sticky_scope'])
            context['project_list'] = context['project_list'].filter(scope = context['sticky_scope'])
        return context

tasksapp/views/scope.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from django.urls import reverse_lazy

from django.views.generic.edit import CreateView, DeleteView, UpdateView

from tasksapp.models import Scope
from django.views.generic.list import ListView

class CreateView(LoginRequiredMixin, CreateView):
    model = Scope
    fields = '__all__'
    
    def form_valid(self, form):
        # add success message
        messages.success(self.request, 'Scope created successfully.')
        return super().form_valid(form)

class UpdateView(LoginRequiredMixin, UpdateView):
    model = Scope
    fields = '__all__'
    
    def form_valid(self, form):
        # add success message
        messages.success(self.request, 'Scope saved successfully.')
        return super().form_valid(form)

class DeleteView(LoginRequiredMixin, DeleteView):
    model = Scope
    success_url = reverse_lazy('scope-list')

class ListView(LoginRequiredMixin, ListView):
    model = Scope

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        if 'sticky_scope' in self.request.session:
            context['sticky_scope'] = Scope.objects.get(pk = self.request.session['sticky_scope'])
        return context

tasksapp/templates/tasksapp/milestone/finish.html
{% extends "tasksapp/milestone/layout.html" %}
{% load bootstrap4 %}

{% block extra_head %}
{% include 'includes/fontawesome.html' %}
{{ form.media }}
{% endblock %}

{% block item_title %}
{% if milestone.project %}
{{ milestone.project }}
{% endif %}
{{ milestone }}
{% endblock %}

{% block content %}
<form method="post" class="form">
    {% csrf_token %}
    <div class="row">
    	<div class="col-auto">
	        {% url 'milestone-list' as back_url %}
            {% bootstrap_button '<i class="far fa-caret-square-left fa-2x"></i>' button_type="link" button_class="btn-secondary btn-block" href=back_url %}
    	</div>
    	<div class="col-8 col-md-9 col-xl-10">
		    {% bootstrap_field form.name show_label=False size='large' %}
    	</div>
    	<div class="col-auto">
            {% bootstrap_button '<i class="fas fa-check-square fa-2x"></i>' button_type="submit" button_class="btn-primary btn-block" %}
    	</div>
    </div>
    <div class="row">
    	<div class="col-12 col-lg-9">
    		{% bootstrap_field form.description %}
    	</div>
    	<div class="col-12 col-lg-3">
    		{% bootstrap_field form.project %}
    		{% bootstrap_label "Date and Time passed" label_for="datetime_to_pass" %}
    		{% bootstrap_field form.datetime_to_pass show_label=False %}
    	</div>
    </div>
    <div class="row">
    	<div class="col-12">
    		<h4>enthaltene Tasks</h4>
    		
{% for task in task_list %}
<div class="row">
	<div class="col-10">
		<div class="row">
			<div class="col-1">{{ task.priority_sum }}</div>
			<div class="col-7"><a href="{% url 'task-edit' task.pk %}">{{ task }}</a></div>
			<div class="col-2">{{ task.status }}</div>
			<div class="col-2">{{ task.remainingEffort }}</div>
			<div class="col-9 offset-1">
				{% for category in task.categories.all %}
					{% if not forloop.first %}<span>, </span>{% endif %}
					<span>{{ category }}</span>
				{% endfor %}
			</div>
			{% if task.due_date is not None %}
			<div class="col-2">
				{{ task.due_date|date:"SHORT_DATE_FORMAT" }}
			</div>
			{% endif %}
		</div>
	</div>
	<div class="col-2">
		<a class="btn btn-secondary" href="{% url 'pomodoro:index' %}?pomoTask={{ task.pk }}">
			<i class="fas fa-play"></i>
		</a>
		<a class="btn btn-secondary" href="{% url 'task-done' task.pk %}?next={% url 'milestone-finish' milestone.pk %}">
			<i class="fas fa-check-square"></i>
		</a>
		<a class="btn btn-secondary" href="#">
			<i class="fas fa-puzzle-piece"></i>
		</a>
	</div>
</div>
<hr />
{% endfor %}
    	</div>
    </div>
</form>
{% endblock content %}

tasksapp/templates/tasksapp/milestone/layout.html
{% extends "base.html" %}

{% block module_title %}&loz; {% endblock %}
{% block item_title %}Liste{% endblock %}

tasksapp/templates/tasksapp/milestone/report.html
{% extends "tasksapp/milestone/layout.html" %}
{% load bootstrap4 %}
{% load static %}

{% block extra_head %}
{% include 'includes/fontawesome.html' %}
{% endblock %}

{% block item_title %}
{% if milestone.project %}
{{ milestone.project }}
{% endif %}
{{ milestone }}
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-11"><h1>{% if object.project %}{{ object.project }} - {% endif %}{{ object }}</h1></div>
	<div class="col-1">
		{% url 'milestone-list' as back_url %}
		{% bootstrap_button '<i class="far fa-caret-square-left fa-2x"></i>' button_type="link" button_class="btn-secondary btn-block" href=back_url %}
	</div>
</div>
<div class="row">
	<div class="col-12">
		<h4>enthaltene Tasks</h4>

		<div class="row">
			<div class="col-10">
				<div class="row">
					<div class="col-1">Prio</div>
					<div class="col-7">Aufgabe</div>
					<div class="col-2">Status</div>
					<div class="col-2">Restaufwand</div>
					<div class="col-9 offset-1">Kategorien</div>
					<div class="col-2">Fälligkeit</div>
				</div>
			</div>
			<div class="col-2">Action</div>
		</div>

		{% for task in task_list %}
		<div class="row">
			<div class="col-10">
				<div class="row">
					<div class="col-1">{{ task.priority_sum }}</div>
					<div class="col-7"><a href="{% url 'task-edit' task.pk %}">{{ task }}</a></div>
					<div class="col-2">{{ task.status }}</div>
					<div class="col-2">{{ task.remainingEffort }}</div>
					<div class="col-9 offset-1">
						{% for category in task.categories.all %}
							{% if not forloop.first %}<span>, </span>{% endif %}
							<span>{{ category }}</span>
						{% endfor %}
					</div>
					{% if task.due_date is not None %}
					<div class="col-2">
						{{ task.due_date|date:"SHORT_DATE_FORMAT" }}
					</div>
					{% endif %}
				</div>
			</div>
			<div class="col-2">
				<a class="btn btn-secondary" href="{% url 'milestone-add-task' object.pk task.pk %}">
					<i class="fas fa-plus-square"></i>
				</a>
			</div>
		</div>
		<hr />
		{% endfor %}
	</div>
</div>
{% endblock content %}

tasksapp/templates/tasksapp/milestone/setup.html
{% extends "tasksapp/milestone/layout.html" %}
{% load bootstrap4 %}
{% load static %}

{% block extra_head %}
{% include 'includes/fontawesome.html' %}
{% endblock %}

{% block item_title %}
{% if milestone.project %}
{{ milestone.project }}
{% endif %}
{{ milestone }}
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-11"><h1>{% if object.project %}{{ object.project }} - {% endif %}{{ object }}</h1></div>
	<div class="col-1">
		{% url 'milestone-list' as back_url %}
		{% bootstrap_button '<i class="far fa-caret-square-left fa-2x"></i>' button_type="link" button_class="btn-secondary btn-block" href=back_url %}
	</div>
</div>
<div class="row">
	<div class="col-12">
		<h4>verfügbare Tasks</h4>

		<div class="row">
			<div class="col-10">
				<div class="row">
					<div class="col-1">Prio</div>
					<div class="col-7">Aufgabe</div>
					<div class="col-2">Status</div>
					<div class="col-2">Restaufwand</div>
					<div class="col-9 offset-1">Kategorien</div>
					<div class="col-2">Fälligkeit</div>
				</div>
			</div>
			<div class="col-2">Action</div>
		</div>

		{% for task in task_list %}
		<div class="row">
			<div class="col-10">
				<div class="row">
					<div class="col-1">{{ task.priority_sum }}</div>
					<div class="col-7"><a href="{% url 'task-edit' task.pk %}">{{ task }}</a></div>
					<div class="col-2">{{ task.status }}</div>
					<div class="col-2">{{ task.remainingEffort }}</div>
					<div class="col-9 offset-1">
						{% for category in task.categories.all %}
							{% if not forloop.first %}<span>, </span>{% endif %}
							<span>{{ category }}</span>
						{% endfor %}
					</div>
					{% if task.due_date is not None %}
					<div class="col-2">
						{{ task.due_date|date:"SHORT_DATE_FORMAT" }}
					</div>
					{% endif %}
				</div>
			</div>
			<div class="col-2">
				<a class="btn btn-secondary" href="{% url 'milestone-add-task' object.pk task.pk %}">
					<i class="fas fa-plus-square"></i>
				</a>
			</div>
		</div>
		<hr />
		{% endfor %}
	</div>
</div>
{% endblock content %}